### ISSUE TITLE
Actividad 1 mapa mental 

### ISSUE THREAD

**Issue by Abisaylopez** [SistemasTecTlaxiaco/actividad-4-mapa-mental-Abisaylopez#1]
[comunicación oral y escrita .pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-Abisaylopez/files/9602643/comunicacion.oral.y.escrita.pdf)
Alumno Abisay López Mendoza 1bs

**Comment by AmeliReyesHernandez** [comment]
17.6 de 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
